"""empty message

Revision ID: 1273cae33646
Revises: abd35c351474
Create Date: 2021-12-23 12:41:33.992204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1273cae33646'
down_revision = 'abd35c351474'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'born')
    op.drop_column('doctors', 'place')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('place', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('doctors', sa.Column('born', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
