"""empty message

Revision ID: 7598638cb2a3
Revises: 4dabc57ff444
Create Date: 2021-12-24 14:40:46.079067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7598638cb2a3'
down_revision = '4dabc57ff444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
