"""empty message

Revision ID: 78fc6e41850e
Revises: 7598638cb2a3
Create Date: 2021-12-24 14:41:51.643084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78fc6e41850e'
down_revision = '7598638cb2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
