"""empty message

Revision ID: 93a9e1b463f8
Revises: 78fc6e41850e
Create Date: 2021-12-24 14:42:32.978560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93a9e1b463f8'
down_revision = '78fc6e41850e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
