"""empty message

Revision ID: 9e28df1b2c30
Revises: df54a3f0191b
Create Date: 2021-12-24 14:43:39.831860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e28df1b2c30'
down_revision = 'df54a3f0191b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
