"""empty message

Revision ID: abd35c351474
Revises: e6ce1b72a0de
Create Date: 2021-12-23 12:31:02.541835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd35c351474'
down_revision = 'e6ce1b72a0de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('born', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'born')
    # ### end Alembic commands ###
