"""empty message

Revision ID: ac5ea1ac3133
Revises: 1273cae33646
Create Date: 2021-12-23 13:17:29.629305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac5ea1ac3133'
down_revision = '1273cae33646'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('place', sa.String(), nullable=True))
    op.add_column('doctors', sa.Column('born', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'born')
    op.drop_column('doctors', 'place')
    # ### end Alembic commands ###
