"""empty message

Revision ID: acd72d29db05
Revises: b0b5bcc8c02b
Create Date: 2021-12-23 13:21:25.685524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acd72d29db05'
down_revision = 'b0b5bcc8c02b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
