"""empty message

Revision ID: df54a3f0191b
Revises: 93a9e1b463f8
Create Date: 2021-12-24 14:43:13.551027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df54a3f0191b'
down_revision = '93a9e1b463f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
